Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.40"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.name = "Kube01"
  end
  config.vm.provision "shell", path: "./provision/create_vm.sh"
end
