Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.56.30"
    config.vm.provider "virtualbox" do |vb|
     vb.name = "Redis01"
  end
  config.vm.provision "shell", path: "./provision/create_vm.sh"
end
