Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.56.20"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "512"
     vb.name = "Mongo01"
  end
  config.vm.provision "shell", path: "./provision/create_vm.sh"
end
