Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.synced_folder "./scripts", "/opt/database/scripts"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.name = "SqlServer01"
  end
  config.vm.provision "shell", path: "./provision/create_vm.sh"
end
